services:
  esmini:
    build:
      context: .
      dockerfile: esmini.Dockerfile
    entrypoint: sleep infinity
    hostname: esmini
    container_name: eba-esmini
    volumes:
      - ./esmini-ws:/esmini-ws
      - ./ros_ws:/ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
  autoware:
    build:
      context: .
      dockerfile: autoware.Dockerfile
    entrypoint: sleep infinity
    environment:
      - DISPLAY
    hostname: autoware
    container_name: eba-autoware
    volumes:
      - ./ros_ws:/ros_ws
      - ./resources:/resources
      - /tmp/.X11-unix:/tmp/.X11-unix
