services:
  esmini:
    build:
      context: .
      dockerfile: esmini-ws.Dockerfile
    entrypoint: sleep infinity
    hostname: esmini
    container_name: eba-esmini
    networks:
      - rosnet
    volumes:
      - ./ros_ws:/ros_ws
      - ./resources:/resources
      - /tmp/.X11-unix:/tmp/.X11-unix
  autoware:
    build:
      context: .
      dockerfile: autoware-ws.Dockerfile
    entrypoint: sleep infinity
    environment:
      - DISPLAY
    hostname: autoware
    container_name: eba-autoware
    networks:
      - rosnet
    volumes:
      - ./autoware_ws/:/autoware_ws
      - ./resources:/resources
      - /tmp/.X11-unix:/tmp/.X11-unix
networks:
  rosnet:
    driver: bridge
