set shell := ["bash" , "-c"]

source_ros := '. /opt/ros/humble/setup.sh'
source_ws := '. ./install/setup.sh'

default:
  just run

deps:
  rosdep install --from-path src --ignore-src -y

build: deps
  colcon build

run: build
  {{source_ros}} && {{source_ws}} && cd /esmini/resources && ros2 run esmini_bridge_autoware esmini_bridge_autoware

debug: build
  {{source_ros}} && {{source_ws}} && cd /esmini/resources && ros2 run esmini_bridge_autoware esmini_bridge_autoware --ros-args --log-level DEBUG
