set shell := ["bash" , "-c"]

source_ros := 'source /opt/ros/humble/setup.bash'
source_ws := 'source ./install/setup.bash'
source_aw := 'source /autoware/install/setup.bash'

default xosc:
  just build
  just run {{xosc}}

deps:
  apt update
  {{source_ros}} && rosdep install --from-path src --ignore-src -y

build:
  {{source_ros}} && colcon build

clean:
  rm -rf install/ build/ log/

run xosc:
  {{source_ros}} && {{source_aw}} && {{source_ws}} && \
    ros2 launch cpp_esmini_bridge_autoware main.yaml xosc:="{{xosc}}"

debug: build
  {{source_ros}} && {{source_ws}} && \
  ros2 run cpp_esmini_bridge_autoware esmini-bridge-autoware \
    --ros-args --log-level DEBUG
