set shell := ["bash" , "-c"]

source_ros := 'source /opt/ros/humble/setup.bash'
source_ws := 'source ./install/setup.bash'

default:
  just run

deps:
  rosdep install --from-path src --ignore-src -y

build: deps
  {{source_ros}} && colcon build

clean:
  rm -rf install/ build/ log/

run: build
  {{source_ros}} && {{source_ws}} && \
    cd /esmini/resources/xosc && \
    ros2 run cpp_esmini_bridge_autoware esmini-bridge-autoware

debug: build
  {{source_ros}} && {{source_ws}} && cd /esmini/resources && ros2 run cpp_esmini_bridge_autoware esmini-bridge-autoware --ros-args --log-level DEBUG
